In [2]:
from PyEMD import EMD
import pylab as plt


from pyhht.visualization import plot_imfs
import numpy as np
import math
#from pyhht.emd import EMD
import matplotlib.pyplot as plt
from tftb.generators import fmconst
from scipy import angle, unwrap
from scipy.signal import hilbert
import pandas as pd
from scipy import signal
import statistics


from scipy.stats import entropy
from math import log, e
import timeit

In [3]:
df=pd.read_excel("C:/Users/Dell/Documents/sem8/Data Set/hacat.xlsx")
a1=df["t"]
list(a1)
import numpy as np
a1ar=np.asarray(a1)
type(a1ar)
#print(a1ar)
a2=df["modes"]
list(a2)
import numpy as np
a2ar=np.asarray(a2)
type(a2ar)
#print(a2ar)
x=a1ar+a2ar
#plt.plot(a1ar,a2ar);

In [4]:
df=pd.read_excel("C:/Users/Dell/Documents/sem8/Data Set/MCF7_100_S.xlsx")
a1=df["t"]
list(a1)
import numpy as np
a1ar=np.asarray(a1)
type(a1ar)
#print(a1ar)
a3=df["modes"]
list(a3)
import numpy as np
a3ar=np.asarray(a3)
type(a3ar)
#print(a2ar)
x=a1ar+a3ar
#plt.plot(a1ar,a3ar);



In [5]:
df=pd.read_excel("C:/Users/Dell/Documents/sem8/Data Set/231_s.xlsx")
a1=df["t"]
list(a1)
import numpy as np
a1ar=np.asarray(a1)
type(a1ar)
#print(a1ar)
a4=df["modes"]
list(a4)
import numpy as np
a4ar=np.asarray(a4)
type(a4ar)
#print(a2ar)
x=a1ar+a4ar
#plt.plot(a1ar,a4ar);


In [6]:
print('Correlation between hacat and Mcf')
np.corrcoef(a3ar[1:1300],a2ar[1:1300])


Correlation between hacat and Mcf


array([[1.        , 0.44119276],
       [0.44119276, 1.        ]])

In [7]:
print('Correlation between hacat and 231_s')
np.corrcoef(a4ar[1:1300],a2ar[1:1300])

Correlation between hacat and 231_s


array([[1.        , 0.04598248],
       [0.04598248, 1.        ]])

In [8]:
def entropy4(labels, base=None):
  value,counts = np.unique(labels, return_counts=True)
  norm_counts = counts / counts.sum()
  base = e if base is None else base
  return -(norm_counts * np.log(norm_counts)/np.log(base)).sum()


In [9]:
print('Entrophy for Hacat')
print(entropy4(a2ar))
print('Entrophy for Mcf')
print(entropy4(a3ar))
print('Entrophy for 231_s')
print(entropy4(a4ar))

Entrophy for Hacat
7.2531523126789565
Entrophy for Mcf
7.436665942245128
Entrophy for 231_s
7.167487330271948


In [10]:
print('Correlation between 231_s and Mcf')
np.corrcoef(a3ar[1:1300],a4ar[1:1300])


Correlation between hacat and Mcf


array([[1.        , 0.69839578],
       [0.69839578, 1.        ]])